export default {
  Offers: [
    {
      uuid: 1,
      name: 'Minecraft Offers',
      offer_types: [
        {
          uuid: 1,
          name: 'Starter',
          type: 'shared',
          models: [
            {
              uuid: 1,
              name: 'Starter-2048',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 2048,
              disk_space: {
                current_disk_space: 0,
                min: 0,
                max: 0,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: false,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              modded_servers_allowed: true,
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: false,
              sla: 99.95,
              monthly_price: 0.0,
              hourly_price: 0.0,
            },
            {
              uuid: 2,
              name: 'Starter-3072',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 3072,
              disk_space: {
                current_disk_space: 0,
                min: 0,
                max: 0,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: false,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              modded_servers_allowed: true,
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: false,
              sla: 99.95,
              monthly_price: 0.0,
              hourly_price: 0.0,
            },
            {
              uuid: 3,
              name: 'Starter-4096',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 4096,
              disk_space: {
                current_disk_space: 0,
                min: 0,
                max: 0,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: false,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              modded_servers_allowed: true,
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: false,
              sla: 99.95,
              monthly_price: 0.0,
              hourly_price: 0.0,
            },
            {
              uuid: 4,
              name: 'Starter-6144',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 6144,
              disk_space: {
                current_disk_space: 0,
                min: 0,
                max: 0,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: false,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              modded_servers_allowed: true,
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: false,
              sla: 99.95,
              monthly_price: 0.0,
              hourly_price: 0.0,
            },
            {
              uuid: 5,
              name: 'Starter-8192',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 8192,
              disk_space: {
                current_disk_space: 0,
                min: 0,
                max: 0,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: false,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              modded_servers_allowed: true,
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: false,
              sla: 99.95,
              monthly_price: 0.0,
              hourly_price: 0.0,
            },
            {
              uuid: 6,
              name: 'Starter-10240',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 10240,
              disk_space: {
                current_disk_space: 0,
                min: 0,
                max: 0,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: false,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              modded_servers_allowed: true,
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: false,
              sla: 99.95,
              monthly_price: 0.0,
              hourly_price: 0.0,
            },
            {
              uuid: 7,
              name: 'Starter-12288',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 12288,
              disk_space: {
                current_disk_space: 0,
                min: 0,
                max: 0,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: false,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              modded_servers_allowed: true,
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: false,
              sla: 99.95,
              monthly_price: 0.0,
              hourly_price: 0.0,
            },
          ],
        },
        {
          uuid: 2,
          name: 'Premium',
          type: 'Dedicated',
          models: [
            {
              uuid: 1,
              name: 'Premium-2048',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 2048,
              disk_space: {
                current_disk_space: 20000,
                min: 20000,
                max: 120000,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: true,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              modded_servers_allowed: true,
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: true,
              sla: 99.95,
              monthly_price: 0.0,
              hourly_price: 0.0,
            },
            {
              uuid: 2,
              name: 'Premium-4096',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 4096,
              disk_space: {
                current_disk_space: 40000,
                min: 40000,
                max: 120000,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: true,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              modded_servers_allowed: true,
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: true,
              sla: 99.95,
              monthly_price: 0.0,
              hourly_price: 0.0,
            },
            {
              uuid: 3,
              name: 'Premium-8192',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 8192,
              disk_space: {
                current_disk_space: 80000,
                min: 80000,
                max: 120000,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: true,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              modded_servers_allowed: true,
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: true,
              sla: 99.95,
              monthly_price: 0.0,
              hourly_price: 0.0,
            },
            {
              uuid: 4,
              name: 'Premium-12288',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 12288,
              disk_space: {
                current_disk_space: 120000,
                min: 120000,
                max: 240000,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: true,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              modded_servers_allowed: true,
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: true,
              sla: 99.95,
              monthly_price: 0.0,
              hourly_price: 0.0,
            },
          ],
        },
      ],
    },
    {
      uuid: 2,
      name: 'Minecraft Proxy Offers',
      offer_types: [
        {
          uuid: 1,
          name: 'Starter',
          type: 'shared',
          models: [
            {
              uuid: 1,
              name: 'Bungeecord-1024',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 1024,
              disk_space: {
                current_disk_space: 10000,
                min: 10000,
                max: 20000,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: false,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: false,
              sla: 99.95,
              monthly_price: 1.99,
              hourly_price: 0.004,
            },
            {
              uuid: 2,
              name: 'Bungeecord-2048',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 2048,
              disk_space: {
                current_disk_space: 20000,
                min: 20000,
                max: 40000,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: false,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: false,
              sla: 99.95,
              monthly_price: 3.99,
              hourly_price: 0.008,
            },
            {
              uuid: 3,
              name: 'Waterfall-1024',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 1024,
              disk_space: {
                current_disk_space: 10000,
                min: 10000,
                max: 20000,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: false,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: false,
              sla: 99.95,
              monthly_price: 1.99,
              hourly_price: 0.004,
            },
            {
              uuid: 4,
              name: 'Waterfall-2048',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 2048,
              disk_space: {
                current_disk_space: 20000,
                min: 20000,
                max: 20000,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: false,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: false,
              sla: 99.95,
              monthly_price: 3.99,
              hourly_price: 0.008,
            },
          ],
        },
        {
          uuid: 2,
          name: 'Premium',
          type: 'Dedicated',
          models: [
            {
              uuid: 1,
              name: 'Bungeecord-2048',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 2048,
              disk_space: {
                current_disk_space: 20000,
                min: 20000,
                max: 120000,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: true,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: true,
              sla: 99.95,
              monthly_price: 6.99,
              hourly_price: 0.0014,
            },
            {
              uuid: 2,
              name: 'Waterfall-2048',
              players_slots: 64000,
              plugins_limit: 64000,
              ram_memory: 2048,
              disk_space: {
                current_disk_space: 20000,
                min: 20000,
                max: 40000,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              port: {
                current_nb_port: 0,
                min: 0,
                max: 5,
                monthly_price: 0.0,
                hourly_price: 0.0,
              },
              custom_domain_address: true,
              dedicated_ip_address: {
                dedicated_ip: true,
                monthly_price: 1.99,
                hourly_price: 0.00035,
              },
              automated_backups: true,
              planned_tasks: true,
              prioritized_support: true,
              sla: 99.95,
              monthly_price: 6.99,
              hourly_price: 0.014,
            },
          ],
        },
      ],
    },
  ],
}
